nelmio_api_doc:
    documentation:
        info:
            title: Blog platform API
            description: Documentation for REST API lab
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        paths:
            /api/login:
                post:
                    tags:
                        - Login
                    summary: Login and getting JWT token
                    security: []
                    requestBody:
                        description: Credentinals
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            example: user@example.com
                                        password:
                                            type: string
                                            example: password123
                    responses:
                        '200':
                            description: Successful login
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                description: Your JWT token
                        '401':
                            description: Invalid Credentinals

        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
