name: CI

on:
    push:
        branches:
          - feat/*
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build
              env:
                JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
              run: docker compose -f docker-compose.ci.yaml build

            - name: Generate JWT keys
              env:
                JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
              run: |
                docker compose -f docker-compose.ci.yaml run --rm php chmod +x bin/console

                docker compose -f docker-compose.ci.yaml run --rm \
                -e JWT_PASSPHRASE=$JWT_PASSPHRASE \
                php bin/console lexik:jwt:generate-keypair
            
            - name: Run tests with coverage
              env:
                JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
              run: |
                docker compose -f docker-compose.ci.yaml up -d
                
                sleep 10

                docker compose exec php bin/console doctrine:migrations:migrate --no-interaction
                
                docker compose -f docker-compose.ci.yaml run --rm \
                -e PHP_PCOV_ENABLED=1 \
                -e JWT_PASSPHRASE=$JWT_PASSPHRASE \
                php bin/phpunit --configuration phpunit.dist.xml --coverage-text --coverage-clover=coverage.xml --colors=never
            
            - name: Check coverage threshold
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                filename: coverage.xml
                fail_below_min: true
                threshold: '60 80'
